version: "3.3"
services:
  cassandra:
    image: bitnami/cassandra:latest
    container_name: cassandra
    hostname: cassandra
    ports:
      - "7000:7000"
      - "9042:9042"
      - "7001:7001"
      - "7199:7199"
  user:
    ports:
      - "8080:8080"
    container_name: user
    build:
      context: ./docker
      dockerfile: Dockerfile
    depends_on:
      - cassandra